### ISSUE TITLE
Spike: TOML

### ISSUE THREAD

**Issue by esacteksab** [esacteksab/gh-tp#24]
I have apprehensions about supporting an OSS project that uses YAML given the incredible likelihood that more than one user will have an issue related to white space. TOML might be a better alternative.

The current config `.tp`

```yaml
binary: tofu
planfile: "tfplan.out"
mdfile: "tfplan.md"
no-color: true
```

It's incredibly rudimentary, long-term, I'm imagining a scenario where a user might have a config file in their home directory (e.g. `~/.tp.toml`) but then possibly via #21 a user would do a `tp init` in a repo. The file in the home directory would be "global", where the file in the local repo, is just that, local. Settings specific to that repo. Local settings would have priority over the more global settings.

But for that global file to exist, I'm imaging something like

```yaml
# ~/.tp.toml

binary: tofu
no-color: false
planfile: 'plan.out'
mdfile: 'plan.md'

repos:
  - name: esacteksab/gh-tp
    binary: tofu
    planfile: 'tfplan.out'
    mdfile: 'tfplan.md'
    no-color: true

  - name: org/repo
    binary: terraform
    planfile: 'plan.out'
    mdfile: 'plan.md'
    no-color: false
```

A file in the repo might look something like

```yaml
# .tp.toml

binary: terraform
no-color: true
planfile: 'out.plan'
mdfile: 'out.md'
```

With the local declaration the file names could align with values already existing in `.gitignore` where `gh tp` replaces their current workflow.
