### ISSUE TITLE
We should test that this is a valid/expected value (bool)

### ISSUE THREAD

**Issue by esacteksab** [esacteksab/gh-tp#81]
In file testdata/badParameterTypes/.tp.toml
undefined

**Comment by esacteksab** [comment]
I've been thinking more and more about this. Go being a typed language, it's _hard_ to _not_ put a `bool` for `verbose` when creating the config file. I _think_ Viper is doing some terrible shit, because if I pass it a value that isn't `true` or `false`, it _does_ return an error

```toml
binary = "terraform"
#binary = "tofu"
planFile = "plan.out"
mdFile = "plan.md"
# noColor = true
verbose = fukd
```

Returns `ERRO While parsing config: toml: expected 'false'`. I'm not sure why it expected `false`.

But if I pass a string to `verbose`

```toml
binary = "terraform"
#binary = "tofu"
planFile = "plan.out"
mdFile = "plan.md"
# noColor = true
verbose = 'fukd'
```

It acts as if `verbose = false`.

If I pass it a `string` with a value of `'true'` it coerces it into a bool:

```toml
binary = "terraform"
#binary = "tofu"
planFile = "plan.out"
mdFile = "plan.md"
# noColor = true
verbose = 'true'
```

Returns verbose output.

```bash
... truncated for brevity

2025/03/23 19:51:58 DEBU <cmd/tools.go:48> Plan file plan.out was created.
✔  Plan Created...
2025/03/23 19:51:58 DEBU <cmd/tools.go:48> Markdown file plan.md was created.
✔  Markdown Created...
```

I guess there are worse things than coercing it into a bool. I'd rather it respect the type and return `incorrect type: not a bool`.
